<?php
$form = $this->form;
$articleForm = $this->addArticleFrom;
?>
<?php echo $this->partial('layout/partial/navigation'); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('Invoice.add.heading')?></h1>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->formErrors($form); ?>
        </div>
    </div>
    <div class="row">
        <form id="invoiceForm" class="form-horizontal" method="post" action="<?php echo $this->url('add-invoice', [], true)?>" >
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Invoice.add.panel1.label')?>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('documentNumber'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('documentNumber'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('documentDate'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('documentDate'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('delayPercent'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('delayPercent'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('deadlineDays'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('deadlineDays'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('deadlineDate'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('deadlineDate'))?>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
            </div>
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Invoice.add.panel2.label')?>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('client'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formSelect($form->get('client'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('subjectName'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('subjectName'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('subjectEmail'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('subjectEmail'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('subjectRegNo'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('subjectRegNo'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('subjectVatNo'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('subjectVatNo'))?>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
            </div>
            <div class="col-lg-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Invoice.add.panel3.label')?>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('referenceNumber'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('referenceNumber'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('vat'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formSelect($form->get('vat'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('amount'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('amount'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('vatAmount'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('vatAmount'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('amountVat'))?>
                            <div class="col-sm-7">
                                <?php echo $this->formText($form->get('amountVat'))?>
                            </div>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
            </div>
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Invoice.add.panel1.label')?>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="col-sm-2">
                            <?php echo $this->formSelect($articleForm->get('articleType'))?>
                        </div>
                        <div class="col-sm-2">
                            <?php echo $this->formSelect($articleForm->get('category'))?>
                        </div>
                        <div class="col-sm-2">
                            <?php echo $this->formSelect($articleForm->get('brand'))?>
                        </div>
                        <div class="col-sm-2">
                            <?php echo $this->formSelect($articleForm->get('article'))?>
                        </div>
                        <div class="col-sm-1">
                            <a class="btn btn-default btn-xs" id="add-article-row" href="javascript:void(0)"><i class="fa fa-plus fa-fws"></i>  <?php echo $this->translate('Invoice.add.addArticleRow')?></a>
                        </div>
                        <div class="col-sm-3 pull-right">
                            <a class="btn btn-default btn-xs" id="add-empty-row" href="javascript:void(0)" ><i class="fa fa-plus fa-fws"></i>  <?php echo $this->translate('Invoice.add.addEmptyRow')?></a>
                        </div>
                    </div>
                    <!-- /.panel-body -->
                </div>
            </div>
        </form>
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
    Validator.initClientForm();
</script>