<?php
use Application\Controller\ClientController;
use Application\Controller\InvoiceController;
use Application\Entity\Role;

echo $this->partial('layout/partial/datepicker-head.phtml');
$invoices = $this->invoices;
$filterForm = $this->filterForm;
?>
<?php echo $this->partial('layout/partial/navigation', array('navKey' => $this->navKey)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('Invoice.list.heading')?></h1>
        </div>
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $this->translate('FilterForm.Heading')?>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a id="openFilter" style="display: none" class="btn btn-default btn-xs" href="javascript:void(0)" ><i class="fa fa-plus fa-fws"></i> </a>
                            <a id="closeFilter" class="btn btn-default btn-xs" href="javascript:void(0)" ><i class="fa fa-minus fa-fws"></i> </a>
                        </div>
                    </div>
                </div>
                <div  id="filterBody" class="panel-body">
                    <form id="filterForm" class="form-horizontal" method="get" action="">
                        <div class="col-lg-12">
                            <div class="col-lg-1">
                                <?php echo $this->formText($filterForm->get('entityId'))?>
                            </div>
                            <div class="col-lg-1">
                                <?php echo $this->formText($filterForm->get('entityNumber'))?>
                            </div>
                            <div class="col-lg-2">
                                <div class="col-lg-3">
                                    <span><?php echo $this->translate('Filter.form.fromDate.label')?></span>
                                </div>
                                <div class="col-lg-9">
                                    <?php echo $this->formText($filterForm->get('fromDate'))?>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <div class="col-lg-3">
                                    <span><?php echo $this->translate('Filter.form.toDate.label')?></span>
                                </div>
                                <div class="col-lg-9">
                                    <?php echo $this->formText($filterForm->get('toDate'))?>
                                </div>
                            </div>
                            <?php if($this->user->isMaster() || $this->user->getRoles()->last()->getRoleId() == Role::ROLE_ADMIN):?>
                                <div class="col-lg-2">
                                    <?php echo $this->formSelect($filterForm->get('invoiceUser'))?>
                                </div>
                            <?php endif;?>
                            <div class="col-lg-3">
                                <div class="col-lg-3">
                                    <?php echo $this->formCheckbox($filterForm->get('pending'))?> <?php echo $this->translate('Invoice.filterForm.status.pending.label')?>
                                </div>
                                <div class="col-lg-5">
                                    <?php echo $this->formCheckbox($filterForm->get('archived'))?> <?php echo $this->translate('Invoice.filterForm.status.archived.label')?>
                                </div>
                                <div class="col-lg-4">
                                    <?php echo $this->formCheckbox($filterForm->get('confirmed'))?> <?php echo $this->translate('Invoice.filterForm.status.confirmed.label')?>
                                </div>
                            </div>
                        </div><br/><br/>
                        <div class="col-lg-12">
                            <div class="col-lg-2">
                                <?php echo $this->formText($filterForm->get('clientName'))?>
                            </div>
                            <div class="col-lg-9">

                            </div>
                            <div class="col-lg-1">
                                <div class="form-actions pull-right">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <button class="btn btn-primary btn-xs" id="submit"  type="submit">
                                                <i class="fa fa-filter"></i>
                                                <?php echo $this->translate('FilterForm.saveButton')?>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->errorMessages($this->errorMessages); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Invoice.list.TableHeading')?>
                    <?php if ($this->isAllowed(InvoiceController::AUTHORIZE_CLASS . 'add-invoice')):?>
                        <div class="pull-right">
                            <div class="btn-group">
                                <a class="btn btn-default btn-xs" href="<?php echo $this->url('add-invoice', [], true)?>" ><i class="fa fa-plus fa-fws"></i>  <?php echo $this->translate('Invoice.list.addInvoice')?></a>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" >
                        <thead>
                        <tr>
                            <th><?php echo $this->translate('Invoice.list.tableTh.id')?></th>
                            <th><?php echo $this->translate('Invoice.list.tableTh.number')?></th>
                            <th><?php echo $this->translate('Invoice.list.tableTh.date')?></th>
                            <th><?php echo $this->translate('Invoice.list.tableTh.clientName')?></th>
                            <th><?php echo $this->translate('Invoice.list.tableTh.amount')?></th>
                            <th><?php echo $this->translate('Invoice.list.tableTh.status')?></th>
                            <th><?php echo $this->translate('Invoice.list.tableTh.paymentStatus')?></th>
                            <th><?php echo $this->translate('Invoice.list.tableTh.actions')?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($invoices as $invoice): /* @var $invoice \Application\Entity\Document\Invoice */?>
                            <tr>
                                <td><?php echo $invoice->getId() ?></td>
                                <td><?php echo $invoice->getDocumentNumber() ?></td>
                                <td><?php echo $invoice->getDocumentDate()->format($invoice->getDateFormat()) ?></td>
                                <td><?php echo $invoice->getSubjectName() ?></td>
                                <td><?php echo $invoice->getAmount() ?></td>
                                <td><?php echo $this->statuses[$invoice->getStatus()] ?></td>
                                <td><?php echo $this->paymentStatuses[$invoice->getPaymentStatus()]?></td>
                                <td>
                                    <?php if ($this->isAllowed(InvoiceController::AUTHORIZE_CLASS . 'edit-invoice')):?>
                                        <a href="<?php echo $this->url('edit-invoice', ['id' => $invoice->getId()], true)?>" class="btn btn-xs btn-success" rel="tooltip"><i class="fa fa-save"></i> <?php echo $this->translate('Invoice.row.action.editButton')?></a>
                                    <?php endif;?>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        </tbody>
                        <tfoot>
                        <td colspan="8">
                            <div class="pull-right">
                                <?php echo $this->paginationControl($invoices, 'Sliding', 'application/paginator')?>
                            </div>
                        </td>
                        </tfoot>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>

<!-- /#page-wrapper -->
<script type="text/javascript">
    $(document).ready(function() {

    });
</script>