<?php
use Application\Controller\InvoiceController;

$form = $this->form;
if(!$this->isAllowed(InvoiceController::AUTHORIZE_CLASS . 'edit-invoice-setting')){
    $form->disableFields();
}
?>
<?php echo $this->partial('layout/partial/navigation', array('navKey' => $this->navKey)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('InvoiceSetting.edit.heading')?></h1>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->errorMessages($this->errorMessages); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('InvoiceSetting.edit.heading')?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <form id="invoiceSettingForm" class="form-horizontal" method="post" action="<?php echo $this->url('edit-invoice-setting', [], true)?>">
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('prefix'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('prefix'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('delayPercent'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('delayPercent'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('suffix'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('suffix'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('deadlineDays'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('deadlineDays'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('nextNumber'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('nextNumber'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('dateFormat'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formSelect($form->get('dateFormat'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('languageCode'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formSelect($form->get('languageCode'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('vat'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formSelect($form->get('vat'))?>
                            </div>
                        </div>
                        <div class="form-actions pull-right">
                            <div class="row">
                                <div class="col-sm-12">
                                    <a href="<?php echo $this->url('home', [], true)?>" class="btn btn-default">
                                        <?php echo $this->translate('InvoiceSetting.edit.cancelButton')?>
                                    </a>
                                    <?php if ($this->isAllowed(InvoiceController::AUTHORIZE_CLASS . 'edit-invoice-setting')):?>
                                        <button class="btn btn-primary" id="submit"  type="submit">
                                            <i class="fa fa-save"></i>
                                            <?php echo $this->translate('InvoiceSetting.edit.saveButton')?>
                                        </button>
                                    <?php endif;?>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
    Validator.initInvoiceSettingForm();
</script>