<?php
use Application\Controller\ArticleController;

$itemSettingForm = $this->itemSettingForm;
$serviceSettingForm = $this->serviceSettingForm;
if(!$this->isAllowed(ArticleController::AUTHORIZE_CLASS . 'edit-article-setting')){
    $itemSettingForm->disableFields();
    $serviceSettingForm->disableFields();
}
?>
<?php echo $this->partial('layout/partial/navigation', array('navKey' => $this->navKey)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('ArticleSetting.edit.heading')?></h1>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-12">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->errorMessages($this->errorMessages); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('ArticleSetting.edit.heading')?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tabs-1" data-toggle="tab"><?php echo $this->translate('ArticleSetting.edit.tabs.itemSettings')?></a></li>
                        <li><a href="#tabs-2" data-toggle="tab"><?php echo $this->translate('ArticleSetting.edit.tabs.serviceSettings')?></a></li>
                    </ul>
                    <br/>
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="tabs-1">
                            <form id="itemSettingForm"  class="form-horizontal" method="post" action="<?php echo $this->url('edit-article-setting', ['id' => $this->itemSettingId], true)?>">
                                <div class="form-group">
                                    <?php echo $this->formLabel($itemSettingForm->get('vat'))?>
                                    <div class="col-sm-7">
                                        <?php echo $this->formSelect($itemSettingForm->get('vat'))?>
                                    </div>
                                    <?php if ($this->isAllowed(ArticleController::AUTHORIZE_CLASS . 'add-vat')):?>
                                        <div class="col-sm-1">
                                            <div class="row text-center">
                                                <a class="btn btn-default btn-xs add-modal-vat item" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('tooltip.add-vat')?>"  href="javascript:void(0)" ><i class="fa fa-plus fa-fws"></i> </a>
                                            </div>
                                        </div>
                                    <?php endif;?>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formLabel($itemSettingForm->get('unit'))?>
                                    <div class="col-sm-7">
                                        <?php echo $this->formSelect($itemSettingForm->get('unit'))?>
                                    </div>
                                    <?php if ($this->isAllowed(ArticleController::AUTHORIZE_CLASS . 'add-unit')):?>
                                        <div class="col-sm-1">
                                            <div class="row text-center">
                                                <a class="btn btn-default btn-xs add-modal-unit item" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('tooltip.add-unit')?>"  href="javascript:void(0)" ><i class="fa fa-plus fa-fws"></i> </a>
                                            </div>
                                        </div>
                                    <?php endif;?>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formLabel($itemSettingForm->get('quantity'))?>
                                    <div class="col-sm-7">
                                        <?php echo $this->formText($itemSettingForm->get('quantity'))?>
                                    </div>
                                </div>
                                <div class="form-actions pull-right">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <a href="<?php echo $this->url('home', [], true)?>" class="btn btn-default btn-sm">
                                                <?php echo $this->translate('ArticleSetting.edit.cancelButton')?>
                                            </a>
                                            <?php if ($this->isAllowed(ArticleController::AUTHORIZE_CLASS . 'edit-article-setting')):?>
                                                <button class="btn btn-primary btn-sm" id="submit"  type="submit">
                                                    <i class="fa fa-save"></i>
                                                    <?php echo $this->translate('ArticleSetting.edit.saveButton')?>
                                                </button>
                                            <?php endif;?>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="tab-pane fade" id="tabs-2">
                            <form id="serviceSettingForm" class="form-horizontal" method="post" action="<?php echo $this->url('edit-article-setting', ['id' => $this->serviceSettingId], true)?>">
                                <div class="form-group">
                                    <?php echo $this->formLabel($serviceSettingForm->get('vat'))?>
                                    <div class="col-sm-7">
                                        <?php echo $this->formSelect($serviceSettingForm->get('vat'))?>
                                    </div>
                                    <?php if ($this->isAllowed(ArticleController::AUTHORIZE_CLASS . 'add-vat')):?>
                                        <div class="col-sm-1">
                                            <div class="row text-center">
                                                <a class="btn btn-default btn-xs add-modal-vat service" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('tooltip.add-vat')?>"  href="javascript:void(0)" ><i class="fa fa-plus fa-fws"></i> </a>
                                            </div>
                                        </div>
                                    <?php endif;?>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formLabel($serviceSettingForm->get('unit'))?>
                                    <div class="col-sm-7">
                                        <?php echo $this->formSelect($serviceSettingForm->get('unit'))?>
                                    </div>
                                    <?php if ($this->isAllowed(ArticleController::AUTHORIZE_CLASS . 'add-unit')):?>
                                        <div class="col-sm-1">
                                            <div class="row text-center">
                                                <a class="btn btn-default btn-xs add-modal-unit service" data-toggle="tooltip" data-placement="top" title="<?php echo $this->translate('tooltip.add-unit')?>" href="javascript:void(0)" ><i class="fa fa-plus fa-fws"></i> </a>
                                            </div>
                                        </div>
                                    <?php endif;?>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formLabel($serviceSettingForm->get('quantity'))?>
                                    <div class="col-sm-7">
                                        <?php echo $this->formText($serviceSettingForm->get('quantity'))?>
                                    </div>
                                </div>
                                <div class="form-actions pull-right">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <a href="<?php echo $this->url('home', [], true)?>" class="btn btn-default btn-sm">
                                                <?php echo $this->translate('ArticleSetting.edit.cancelButton')?>
                                            </a>
                                            <?php if ($this->isAllowed(ArticleController::AUTHORIZE_CLASS . 'edit-article-setting')):?>
                                                <button class="btn btn-primary btn-sm" id="submit"  type="submit">
                                                    <i class="fa fa-save"></i>
                                                    <?php echo $this->translate('ArticleSetting.edit.saveButton')?>
                                                </button>
                                            <?php endif;?>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <div class="col-lg-4"></div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
    Validator.initArticleSettingForm();
</script>