<?php
use Application\Controller\ArticleController;
$form = $this->form;
$units = $this->units; /* @var $company \Application\Entity\Subject\Company */
?>
<?php echo $this->partial('layout/partial/navigation', array('navKey' => $this->navKey)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('Article.unit.list.heading')?></h1>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->errorMessages($this->errorMessages); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Article.unit.list.TableHeading')?>
                    <?php if ($this->isAllowed(ArticleController::AUTHORIZE_CLASS . 'add-unit')):?>
                        <div class="pull-right">
                            <div class="btn-group">
                                <a id="addRow" class="btn btn-default btn-xs" href="#" data-target="#addUnit" data-toggle="modal" ><i class="fa fa-plus fa-fws"></i>  <?php echo $this->translate('Article.unit.list.addRow')?></a>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" id="unitTable">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate('Article.unit.list.tableTh.code')?></th>
                                <th><?php echo $this->translate('Article.unit.list.tableTh.value')?></th>
                                <th><?php echo $this->translate('Article.unit.list.tableTh.status')?></th>
                                <th width="15%"><?php echo $this->translate('Article.unit.list.tableTh.actions')?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($units as $unit):?>
                                <?php echo $this->partial('application/article/partial/unit-row', array('unit' => $unit))?>
                            <?php endforeach;?>
                        </tbody>
                        <tfoot>
                            <td colspan="4">
                                <div class="pull-right">
                                    <?php echo $this->paginationControl($units, 'Sliding', 'application/paginator')?>
                                </div>
                            </td>
                        </tfoot>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>

<div class="modal fade" id="addUnit" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog  modal-lg">
        <div class="row">
            <div class="col-sm-7">
                <div class="modal-content">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Article.unit.list.add.modalHeading')?>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <form id="unitForm" class="form-horizontal" method="post" action="<?php echo $this->url('add-unit', [], true)?>" enctype="multipart/form-data">
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('code'))?>
                                    <div class="col-sm-8">
                                        <?php echo $this->formText($form->get('code'))?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('value'))?>
                                    <div class="col-sm-8">
                                        <?php echo $this->formText($form->get('value'))?>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <?php echo $this->formLabel($form->get('status'))?>
                                    <div class="col-sm-8">
                                        <?php echo $this->formSelect($form->get('status'))?>
                                    </div>
                                </div>
                                <div class="form-actions pull-right">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">
                                                <?php echo $this->translate('Article.unit.list.add.modal.cancelButton')?>
                                            </button>
                                            <button class="btn btn-primary" id="submit"  type="submit">
                                                <i class="fa fa-save"></i>
                                                <?php echo $this->translate('Article.unit.list.add.modal.saveButton')?>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    <!-- /.panel-body -->
                    </div>
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
    $(document).ready(function() {
        Unit.init();
        Validator.initUnitForm();
    });
</script>