<?php
$rowDto = $this->dto; /* @var $rowDto \Application\Domain\DocumentRow\InvoiceRowDto  */
$units = $this->units;
$vats = $this->vats;
$rowId = $rowDto ? $rowDto->getId() : null;
$unitId = $rowDto && $rowDto->getUnit() ? $rowDto->getUnit()->getId() : null;
$vatId = $rowDto && $rowDto->getVat() ? $rowDto->getVat()->getId() : null;
?>
<tr <?php echo $rowId ?> class="invoice-row">
    <th><?php echo $rowDto && $rowDto->getArticle() ? $rowDto->getArticle()->getName() : ''?></th>
    <th><input type="text" name="names[]" class="form-control input-sm name" style="min-width: 70px" value="<?php echo $rowDto ? $rowDto->getName(): '' ?>"></th>
    <th><input type="text" name="quantities[]" class="form-control  input-sm quantity" style="min-width: 70px" value="<?php echo $rowDto ? $rowDto->getQuantity() : 1 ?>"></th>
    <th>
        <select name="units[]" class="form-control input-sm unit" style="min-width: 70px">
            <option value=""><?php echo $this->unitEmptyOption ?></option>
            <?php foreach($units as $unit):?>
                <option value="<?php echo $unit->getId()?>" <?php if($unit->getId() == $unitId):?>selected<?php endif?>><?php echo $unit->getCode()?></option>
            <?php endforeach;?>
        </select>
    </th>
    <th><input type="text" name="prices[]" class="form-control input-sm price" style="min-width: 70px" value="<?php echo $rowDto ? $rowDto->getAmount() : 0?>"></th>
    <th>
        <select name="vats[]" class="form-control input-sm vat" style="min-width: 70px">
            <option value=""><?php echo $this->vatEmptyOption ?></option>
            <?php foreach($vats as $vat):?>
                <option value="<?php echo $vat->getValue()?>" <?php if($vat->getId() == $vatId):?>selected<?php endif?>><?php echo $vat->getCode()?></option>
            <?php endforeach;?>
        </select>
    </th>
    <th><input type="text" name="vatAmounts[]" class="form-control input-sm vatAmount" style="min-width: 70px" readonly value="<?php echo $rowDto ? $rowDto->getVatAmount() : 0 ?>"></th>
    <th><input type="text" name="amounts[]" class="form-control input-sm amount" style="min-width: 70px" readonly value="<?php echo $rowDto ? $rowDto->getAmount() : 0 ?>"></th>
    <th><input type="text" name="amountVats[]" class="form-control input-sm amountVat" style="min-width: 70px" readonly value="<?php echo $rowDto ? $rowDto->getAmountVat() : 0?>"></th>
    <th>
        <a class="btn btn-default btn-xs delete-row" data-id="<?php echo $rowId?>" href="javascript:void(0)" ><i class="fa fa-trash-o fa-fws"></i> </a>
        <input type="hidden" name="invoiceIds[]" class="form-control" value="<?php echo $rowId ?>">
    </th>
</tr>