<form class="form-horizontal" id="id-login" novalidate="novalidate">
    <div class="form-group">
        <label class="col-sm-3 control-label"><?php echo $this->translate('Login.email.label')?></label>
        <div class="col-sm-9">
            <input id="idEmail" type="email" name="email" class="form-control email" required="required">
            <span style="display: none" class="help-block"><i class="fa fa-warning"></i> <?php echo $this->translate('Login.email.help-block')?></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary btn-sm pull-right submit" id="id-submit"><?php echo $this->translate('Login.submitButton.label')?></button>
        </div>
    </div>
</form>