<?php
$form = $this->form;
$email = $this->email;
$password = $this->password;
?>
<?php echo $this->form()->openTag($form) ?>
    <div class="form-group">
        <?php echo $this->formLabel($email) ?>
        <div class="col-sm-9">
            <?php echo $this->formInput($email) ?>
        </div>
    </div>
    <div class="form-group">
        <?php echo $this->formLabel($password) ?>
        <div class="col-sm-9">
            <?php echo $this->formInput($password) ?>
        </div>
    </div>
    <span style="display: none" id="loginError"><i class="fa fa-warning"></i> <?php echo $this->translate('Login.login-error.help-block')?></span>
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
            <input type="submit" name="submit" class="btn btn-primary btn-sm pull-right submit" value="<?php echo $this->translate('login.submitButton')?>">
        </div>
    </div>
<?php echo $this->form()->closeTag() ?>