<?php
$helpBlockMessages = array(
    'firstName' => $this->translate('application.user.register.firstName.help-block'),
    'lastName' => $this->translate('application.user.register.lastName.help-block'),
    'phone' => $this->translate('application.user.register.phone.help-block'),
    'personalCode' => $this->translate('application.user.register.personalCode.help-block'),
    'email' => $this->translate('application.user.register.email.help-block'),
    'password' => $this->translate('application.user.register.password.help-block'),
    'passwordRepeat' => $this->translate('application.user.register.password.help-block'),
    'language' => $this->translate('application.user.register.language.help-block'),
    'role' => $this->translate('application.user.register.role.help-block'),
);
$form = $this->form;
$form->setAttribute('action', $this->url('edit-user', ['id' => $this->user->getId()], true));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'userForm');
?>
<?php echo $this->partial('layout/partial/navigation', array('navKey' => $this->navKey)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('Admin.user.edit.heading')?></h1>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->formErrors($form); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Admin.user.edit.heading')?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form) ?>
                    <?php foreach ($form as $element): ?>
                        <?php if (!$element instanceof Zend\Form\Element\Submit): ?>
                        <?php if($element->getName() == 'password'):?>
                            <div class="form-group">
                                <div class="col-sm-3 control-label">
                                    <a id="changePass" href="#" ><?php echo $this->translate('UserForm.changePasswordLink')?></a>
                                    <a id="cancelPass" href="#" style="display: none"><?php echo $this->translate('UserForm.cancelPasswordLink')?></a>
                                </div>
                                <div class="col-sm-9">
                                    <input id="isP" type="hidden" name="isP" value="0">
                                </div>
                            </div>
                            <div id="passwordDiv" style="display: none">
                        <?php endif;?>
                            <div class="form-group">
                                <?php echo $this->formLabel($element) ?>
                                <div class="col-sm-9">
                                    <?php if($element instanceof \Zend\Form\Element\Select):?>
                                        <?php echo $this->formSelect($element) ?>
                                    <?php else:?>
                                        <?php echo $this->formInput($element) ?>
                                    <?php endif;?>
                                    <span style="display: none" class="help-block"><i class="fa fa-warning"></i> <?php echo $helpBlockMessages[$element->getName()]?></span>
                                    <?php if($element->getName() == 'email'):?>
                                        <span style="display: none" class="email-exists"><i class="fa fa-warning"></i> <?php echo $this->translate('Register.emailExists')?></span>
                                    <?php endif;?>
                                </div>
                            </div>
                        <?php if($element->getName() == 'passwordRepeat'):?>
                            </div>
                        <?php endif;?>
                        <?php endif ?>
                    <?php endforeach ?>
                    <div class="form-actions pull-right">
                        <div class="row">
                            <div class="col-sm-12">
                                <a href="<?php echo $this->url('company-user', [], true)?>" class="btn btn-default">
                                    <?php echo $this->translate('Admin.user.edit.cancelButton')?>
                                </a>
                                <button class="btn btn-primary" id="submit"  type="submit">
                                    <i class="fa fa-save"></i>
                                    <?php echo $this->translate('Admin.user.edit.saveButton')?>
                                </button>
                            </div>
                        </div>
                    </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
    Validator.initUserForm(<?php echo $this->user->getId() ?>);
</script>