<?php
$form = $this->form;
?>
<?php echo $this->partial('layout/partial/navigation'); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('Client.add.heading')?></h1>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->formErrors($form); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Client.add.heading')?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <form id="clientForm" class="form-horizontal" method="post" action="<?php echo $this->url('add-client', [], true)?>" >
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('name'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('name'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('code'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('code'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('email'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('email'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('regNo'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('regNo'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('phone'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('phone'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('vatNo'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('vatNo'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('delayPercent'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('delayPercent'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('deadlineDays'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('deadlineDays'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('clientUser'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formSelect($form->get('clientUser'))?>
                            </div>
                            <?php echo $this->formLabel($form->get('status'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formSelect($form->get('status'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('referenceNumber'))?>
                            <div class="col-sm-4">
                                <?php echo $this->formText($form->get('referenceNumber'))?>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($form->get('address'))?>
                            <div class="col-sm-10">
                                <?php echo $this->formTextArea($form->get('address'))?>
                            </div>
                        </div>
                        <div class="form-actions pull-right">
                            <div class="row">
                                <div class="col-sm-12">
                                    <a href="<?php echo $this->url('home', [], true)?>" class="btn btn-default btn-sm">
                                        <?php echo $this->translate('Client.add.cancelButton')?>
                                    </a>
                                    <button class="btn btn-primary btn-sm" id="submit"  type="submit">
                                        <i class="fa fa-save"></i>
                                        <?php echo $this->translate('Client.add.saveButton')?>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <div class="col-lg-2"></div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
    Validator.initClientForm();
</script>