<?php
use Application\Controller\ClientController;
use Application\Entity\Role;

$clients = $this->clients;
$filterForm = $this->filterForm;
?>
<?php echo $this->partial('layout/partial/navigation', array('navKey' => $this->navKey)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('Client.list.heading')?></h1>
        </div>
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <?php echo $this->translate('FilterForm.Heading')?>
                    <div class="pull-right">
                        <div class="btn-group">
                            <a id="openFilter" style="display: none" class="btn btn-default btn-xs" href="javascript:void(0)" ><i class="fa fa-plus fa-fws"></i> </a>
                            <a id="closeFilter" class="btn btn-default btn-xs" href="javascript:void(0)" ><i class="fa fa-minus fa-fws"></i> </a>
                        </div>
                    </div>
                </div>
                <div  id="filterBody" class="panel-body">
                    <form id="filterForm" class="form-horizontal" method="get" action="">
                        <div class="col-lg-1">
                            <?php echo $this->formText($filterForm->get('name'))?>
                        </div>
                        <div class="col-lg-1">
                            <?php echo $this->formText($filterForm->get('code'))?>
                        </div>
                        <div class="col-lg-1">
                            <?php echo $this->formText($filterForm->get('email'))?>
                        </div>
                        <div class="col-lg-2">
                            <?php echo $this->formText($filterForm->get('address'))?>
                        </div>
                        <div class="col-lg-1">
                            <?php echo $this->formText($filterForm->get('regNo'))?>
                        </div>
                        <div class="col-lg-1">
                            <?php echo $this->formText($filterForm->get('vatNo'))?>
                        </div>
                        <?php if($this->user->isMaster() || $this->user->getRoles()->last()->getRoleId() == Role::ROLE_ADMIN):?>
                            <div class="col-lg-2">
                                <?php echo $this->formSelect($filterForm->get('clientUser'))?>
                            </div>
                        <?php endif;?>
                        <div class="col-lg-1">
                            <?php echo $this->formCheckbox($filterForm->get('active'))?> <?php echo $this->translate('Client.filterForm.status.active.label')?>
                        </div>
                        <div class="col-lg-1">
                            <?php echo $this->formCheckbox($filterForm->get('disabled'))?> <?php echo $this->translate('Client.filterForm.status.disabled.label')?>
                        </div>
                        <div class="col-lg-1">
                            <div class="form-actions pull-right">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <button class="btn btn-primary btn-xs" id="submit"  type="submit">
                                            <i class="fa fa-filter"></i>
                                            <?php echo $this->translate('FilterForm.saveButton')?>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->errorMessages($this->errorMessages); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Client.list.TableHeading')?>
                    <?php if ($this->isAllowed(ClientController::AUTHORIZE_CLASS . 'add-client')):?>
                        <div class="pull-right">
                            <div class="btn-group">
                                <a class="btn btn-default btn-xs" href="<?php echo $this->url('add-client', [], true)?>" ><i class="fa fa-plus fa-fws"></i>  <?php echo $this->translate('Client.list.addClient')?></a>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" >
                        <thead>
                        <tr>
                            <th><?php echo $this->translate('Client.list.tableTh.name')?></th>
                            <th><?php echo $this->translate('Client.list.tableTh.code')?></th>
                            <th><?php echo $this->translate('Client.list.tableTh.email')?></th>
                            <th><?php echo $this->translate('Client.list.tableTh.address')?></th>
                            <th><?php echo $this->translate('Client.list.tableTh.regNo')?></th>
                            <th><?php echo $this->translate('Client.list.tableTh.vatNo')?></th>
                            <th><?php echo $this->translate('Client.list.tableTh.status')?></th>
                            <th><?php echo $this->translate('Client.list.tableTh.actions')?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach($clients as $client): /* @var $client \Application\Entity\Subject\Client */?>
                            <tr>
                                <td><?php echo $client->getName() ?></td>
                                <td><?php echo $client->getCode() ?></td>
                                <td><?php echo $client->getEmail() ?></td>
                                <td><?php echo $client->getAddress() ?></td>
                                <td><?php echo $client->getRegistrationNumber() ?></td>
                                <td><?php echo $client->getVatNumber() ?></td>
                                <td><?php echo $this->statuses[$client->getStatus()]?></td>
                                <td>
                                    <?php if ($this->isAllowed(ClientController::AUTHORIZE_CLASS . 'edit-client')):?>
                                        <a href="<?php echo $this->url('edit-client', ['id' => $client->getId()], true)?>" class="btn btn-xs btn-success" rel="tooltip"><i class="fa fa-save"></i> <?php echo $this->translate('Client.row.action.editButton')?></a>
                                    <?php endif;?>
                                </td>
                            </tr>
                        <?php endforeach;?>
                        </tbody>
                        <tfoot>
                        <td colspan="8">
                            <div class="pull-right">
                                <?php echo $this->paginationControl($clients, 'Sliding', 'application/paginator')?>
                            </div>
                        </td>
                        </tfoot>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>

<!-- /#page-wrapper -->
<script type="text/javascript">
    $(document).ready(function() {

    });
</script>