<?php
    $controllers = $this->controllers;
    $adminService = $this->service('Application\Service\Admin'); /* @var $adminService \Application\Service\AdminService  */
    $form = $this->form;
?>
<form id="roleForm" method="post" action="<?php echo $this->action?>">
    <div class="form-group" >
        <?php echo $this->formLabel($form->get('name'))?>
        <div class="col-sm-2">
            <?php echo $this->formText($form->get('name'))?>
            <span style="display: none" class="role-exists"><i class="fa fa-warning"></i> <?php echo $this->translate('Admin.role.role-form.roleExists')?></span>
        </div>
        <?php echo $this->formLabel($form->get('redirectRoute'))?>
        <div class="col-sm-2">
            <?php echo $this->formSelect($form->get('redirectRoute'))?>
        </div>
    </div><br/><br/><br/>

    <table class="table table-bordered" >
        <thead>
        <th><?php echo $this->translate('Admin.role.role-form-table.th.name')?></th>
        <th><?php echo $this->translate('Admin.role.role-form-table.th.action')?></th>
        <th><?php echo $this->translate('Admin.role.role-form-table.th.isAllowed')?></th>
        </thead>
        <tbody>
        <?php foreach($controllers as $controller): /* @var $controller \Application\Entity\Controller */?>
            <tr>
                <td colspan="3"><h4><?php echo $this->translate($controller->getTranslationKey())?></h4></td>
            </tr>

            <?php foreach($controller->getActions() as $action): /* @var $action \Application\Entity\Controller\Action */?>
                <?php
                    $roleAction = $this->role ? $adminService->getRoleActionByRoleAndAction($this->role, $action) : null;
                    $isNavigation = $action->isNavigation();
                ?>
                <tr>
                    <td>
                        <?php if($isNavigation):?>
                            <i class="fa fa-exclamation fa-fws"></i>  <?php echo $this->translate('Admin.role.role-form.navigationAction')?>
                        <?php endif;?>
                    </td>
                    <td><?php echo $this->translate($action->getTranslationKey())?></td>
                    <td>
                        <input id="<?php echo $action->getName()?>" class="isAllowed" type="checkbox" name="isAllowed[<?php echo $action->getId()?>]" <?php if($roleAction && $roleAction->isEnabled()):?>checked<?php endif;?>>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endforeach?>
        </tbody>
        <tfoot>
            <td colspan="3">
                <div class="form-actions pull-right">
                    <div class="row">
                        <div class="col-sm-12">
                            <a href="<?php echo $this->url('role', [], true)?>" class="btn btn-default">
                                <?php echo $this->translate('Admin.role.role-form.cancelButton')?>
                            </a>
                            <button class="btn btn-primary" id="submit"  type="submit">
                                <i class="fa fa-save"></i>
                                <?php echo $this->translate('Admin.role.role-form.saveButton')?>
                            </button>
                        </div>
                    </div>
                </div>
            </td>
        </tfoot>
    </table>
</form>