<?php
    $controllers = $this->controllers;
    $adminService = $this->service('Application\Service\Admin'); /* @var $adminService \Application\Service\AdminService  */
?>
<form id="roleForm" method="post" action="<?php echo $this->action?>">
    <div class="form-group" >
        <label class="col-sm-2 control-label" for="name"><?php echo $this->translate('Admin.role.role-form.name.label')?></label>
        <div class="col-sm-2">
            <input type="text" name="name" id="name" class="form-control" placeholder="<?php echo $this->translate('Admin.role.role-form.name.placeholder')?>" value="<?php echo $this->role ? $this->role->getName() : ''?>">
        </div>
    </div><br/><br/><br/>

    <table class="table table-bordered" >
        <thead>
        <th><?php echo $this->translate('Admin.role.role-form-table.th.name')?></th>
        <th><?php echo $this->translate('Admin.role.role-form-table.th.action')?></th>
        <th><?php echo $this->translate('Admin.role.role-form-table.th.isAllowed')?></th>
        </thead>
        <tbody>
        <?php foreach($controllers as $controller): /* @var $controller \Application\Entity\Controller */?>
            <tr>
                <td colspan="3"><h4><?php echo $this->translate($controller->getTranslationKey())?></h4></td>
            </tr>

            <?php foreach($controller->getActions() as $action): /* @var $action \Application\Entity\Controller\Action */?>
                <?php
                    $roleAction = $this->role ? $adminService->getRoleActionByRoleAndAction($this->role, $action) : null;
                ?>
                <tr>
                    <td></td>
                    <td><?php echo $this->translate($action->getTranslationKey())?></td>
                    <td>
                        <input type="checkbox" name="isAllowed[<?php echo $action->getId()?>]" <?php if($roleAction && $roleAction->isEnabled()):?>checked<?php endif;?>>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endforeach?>
        </tbody>
        <tfoot>
            <td colspan="3">
                <div class="form-actions pull-right">
                    <div class="row">
                        <div class="col-sm-12">
                            <a href="<?php echo $this->url('home', [], true)?>" class="btn btn-default">
                                <?php echo $this->translate('Admin.role.role-form.cancelButton')?>
                            </a>
                            <button class="btn btn-primary" id="submit"  type="submit">
                                <i class="fa fa-save"></i>
                                <?php echo $this->translate('Admin.role.role-form.saveButton')?>
                            </button>
                        </div>
                    </div>
                </div>
            </td>
        </tfoot>
    </table>
</form>