<?php
    $controllers = $this->controllers;
    $action = $this->url('add-role', [], true);
?>
<?php echo $this->partial('layout/partial/navigation', array('navKey' => $this->navKey)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('Admin.role.add.heading')?></h1>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->formErrors($this->form); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Admin.role.add.heading')?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <?php echo $this->partial('application/admin/role/partial/role-form', array('controllers' => $controllers, 'action' => $action, 'role' => null, 'form' => $this->form))?>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->
<script type="text/javascript">
    Validator.initRoleForm();
    Role.init();
</script>