<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Andresson Developments OU">

    <title>skeletonSocialUser</title>

    <!-- Bootstrap Core CSS -->
    <link href="/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/lib/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/css/timeline.css" rel="stylesheet">

    <!-- Social Buttons CSS -->
    <link href="/lib/bootstrap-social/bootstrap-social.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/lib/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
    <body>
        <div id="wrapper">
            <?php echo $this->partial('layout/partial/navigation'); ?>
            <?php echo $this->content; ?>
        </div>
    <!-- /#wrapper -->
        <?php echo $this->inlineScript() ?>
        <!-- jQuery -->
        <script src="/lib/jquery/dist/jquery.min.js"></script>

        <!-- jQuery Validate -->
        <script src="/js/jquery.validate.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="/lib/metisMenu/dist/metisMenu.min.js"></script>

        <!-- Morris Charts JavaScript -->
        <script src="/lib/raphael/raphael-min.js"></script>
        <script src="/lib/morrisjs/morris.min.js"></script>
        <script src="/js/morris-data.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="/js/sb-admin-2.js"></script>
        <script src="/js/_scripts.js"></script>
        <?php
            $availableLanguages = $this->config['languages']['available'];
        ?>
        <?php if(strlen($this->language) > 0 && array_key_exists($this->language, $availableLanguages)):?>
            <script type="text/javascript">
                Common.setLanguage('<?php echo $this->language?>');
            </script>
        <?php endif;?>
        <script type="text/javascript">
            Password.forgotPasswordSuccessMessage = '<?php echo $this->translate('layout.password.forgotPasswordSuccessMessage')?>';
            Password.forgotPasswordErrorMessage = '<?php echo $this->translate('layout.password.forgotPasswordErrorMessage')?>';
            Password.initForgot();
        </script>
    </body>
</html>
