<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Andresson Developments OU">

    <title>skeletonSocialUser</title>

    <!-- Bootstrap Core CSS -->
    <link href="/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/lib/select2/dist/css/select2.min.css" type="text/css" rel="stylesheet" />

    <!-- MetisMenu CSS -->
    <link href="/lib/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/css/timeline.css" rel="stylesheet">

    <!-- Social Buttons CSS -->
    <link href="/lib/bootstrap-social/bootstrap-social.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/lib/morrisjs/morris.css" rel="stylesheet">

    <link href="/lib/datatables/media/css/jquery.dataTables.min.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script src="/js/jquery-2.0.2.min.js"></script>

    <!-- jQuery Validate -->
    <script src="/js/jquery.validate.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="/lib/select2/dist/js/select2.full.js"></script>
    <script type="text/javascript" src="/lib/select2/dist/js/i18n/<?php echo $this->select2code ?>.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/lib/metisMenu/dist/metisMenu.min.js"></script>

    <!-- Morris Charts JavaScript -->
    <script src="/lib/raphael/raphael-min.js"></script>
    <!--        <script src="/lib/morrisjs/morris.min.js"></script>-->
    <!--        <script src="/js/morris-data.js"></script>-->

    <script src="/lib/datatables/media/js/jquery.dataTables.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/js/sb-admin-2.js"></script>

    <script src="/js/_scripts.js"></script>

    <?php
        $availableLanguages = $this->config['languages']['available'];
        $user = $this->currentUser;
        $userId = $user ? $user->getId() : null;
        $companyId = $user && $user->getCompany() ? $user->getCompany()->getId() : null
    ?>
    <?php if(strlen($this->language) > 0 && array_key_exists($this->language, $availableLanguages)):?>
        <script type="text/javascript">
            $('[data-toggle="tooltip"]').tooltip();
            Common.setNoRowsMessage('<?php echo $this->translate('Common.no-rows-message')?>');
            Common.setLanguage('<?php echo $this->language?>');
            Common.setLocale('<?php echo $this->locale?>');
            Common.setCompanyId(<?php echo $companyId ?>);
            Common.setUserId(<?php echo $userId ?>);
            <?php if($userId):?>
            Common.userId = <?php echo $userId?>;
            <?php endif;?>
            <?php if($companyId):?>
            Common.companyId = <?php echo $companyId?>;
            <?php endif;?>
        </script>
    <?php endif;?>
</head>
    <body>
        <div id="wrapper">
            <?php
                $companyName = $this->currentUser() && $this->currentUser()->getCompany() ? $this->currentUser()->getCompany()->getName() : '';
                $companyId = $this->currentUser() && $this->currentUser()->getCompany() ? $this->currentUser()->getCompany()->getId() : null;
                $userId = $this->currentUser() ? $this->currentUser()->getId() : null;
            ?>
            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo ($this->isAllowed(\Application\Controller\CompanyController::AUTHORIZE_CLASS . 'index')) ? $this->url('company', array('id' => $companyId), true) : 'javascript:void(0)'?>"><?php echo $companyName?></a>
                </div>
                <!-- /.navbar-header -->

                <?php echo $this->partial('layout/partial/top-navigation')?>
            <?php echo $this->content; ?>
        </div>
    <!-- /#wrapper -->
        <?php echo $this->inlineScript() ?>
        <!-- jQuery -->
        <script type="text/javascript">
            Password.forgotPasswordSuccessMessage = '<?php echo $this->translate('layout.password.forgotPasswordSuccessMessage')?>';
            Password.forgotPasswordErrorMessage = '<?php echo $this->translate('layout.password.forgotPasswordErrorMessage')?>';
            Password.initForgot();
            FilterForm.init();
        </script>

        <div class="modal fade" id="add-modal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog  modal-lg">
                <div id="add-modal-content" class="row">

                </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
        </div>
    </body>
</html>
