<?php
use Application\Controller\AdminController;
$roles = $this->roles;
?>
<?php echo $this->partial('layout/partial/navigation', array('navKey' => $this->navKey)); ?>
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header"><?php echo $this->translate('Admin.role.list.heading')?></h1>
        </div>
        <!-- /.col-lg-12 -->
        <div class="col-lg-6">
            <?php echo $this->successMessages($this->messages); ?>
            <?php echo $this->errorMessages($this->errorMessages); ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Admin.role.list.TableHeading')?>
                    <?php if ($this->isAllowed(AdminController::AUTHORIZE_CLASS . 'add-role')):?>
                        <div class="pull-right">
                            <div class="btn-group">
                                <a id="addRole" class="btn btn-default btn-xs" href="<?php echo $this->url('add-role', [], true)?>"><i class="fa fa-plus fa-fws"></i>  <?php echo $this->translate('Admin.role.list.addRole')?></a>
                            </div>
                        </div>
                    <?php endif;?>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table class="table table-striped table-bordered table-hover" >
                        <thead>
                            <tr>
                                <th><?php echo $this->translate('Admin.role.list.tableTh.name')?></th>
                                <th><?php echo $this->translate('Admin.role.list.tableTh.actions')?></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach($roles as $role):?>
                                <tr id="row-<?php echo $role->getId()?>">
                                    <td>
                                        <?php echo str_replace($this->company->getId() . '-', '', $role->getRoleId())?>
                                    </td>
                                    <td>
                                        <a href="<?php echo $this->url('edit-role', ['id' => $role->getId()], true)?>" class="btn btn-xs btn-success" rel="tooltip"><i class="fa fa-save"></i> <?php echo $this->translate('Admin.role.row.action.editButton')?></a>
                                    </td>
                                </tr>
                            <?php endforeach;?>
                        </tbody>
                        <tfoot>
                        <td colspan="2">
                            <div class="pull-right">
                                <?php echo $this->paginationControl($roles, 'Sliding', 'application/paginator')?>
                            </div>
                        </td>
                        </tfoot>
                    </table>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
        <!-- /.col-lg-8 -->
    </div>
    <!-- /.row -->
</div>

<!-- /#page-wrapper -->
<script type="text/javascript">
    $(document).ready(function() {
    });
</script>