<?php
$form = $this->form;
$form->setAttribute('action', $this->url('zfcuser/forgot-password', [], true));
$form->setAttribute('class', 'form-horizontal');
$email = $form->get('email');
?>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('forgotPassword.heading')?></h3>
                </div>
                <div class="panel-body" id="forgotPassword">
                    <?php echo $this->form()->openTag($form) ?>
                        <div class="form-group">
                            <?php echo $this->formLabel($email) ?>
                            <div class="col-sm-9">
                                <?php echo $this->formInput($email) ?>
                                <span style="display: none" id="forgot-email-error" class="help-block"><i class="fa fa-warning"></i> <?php echo $this->translate('layout.head.loginForm.error.email')?></span>
                                <span style="display: none" id="forgot-email-not-exists" ><i class="fa fa-warning"></i> <?php echo $this->translate('layout.head.loginForm.error.emailNotExists')?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <?php echo $this->formSubmit($this->form->get('submit')) ?>
                            </div>
                        </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-md-offset-3">
            <a href="<?php echo $this->url('zfcuser/login', [], true)?>"><?php echo $this->translate('Register.backLink')?></a>
        </div>
    </div>
</div>
<script type="text/javascript">
    Password.forgotPasswordSuccessMessage = '<?php echo $this->translate('layout.password.forgotPasswordSuccessMessage')?>';
    Password.forgotPasswordErrorMessage = '<?php echo $this->translate('layout.password.forgotPasswordErrorMessage')?>';
    Password.initForgot();
</script>