<?php
$form = $this->form;
$new = $form->get('password');
$repeat = $form->get('passwordRepeat');
?>


<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('newPassword.heading')?></h3>
                </div>
                <div class="panel-body">
                    <form id="newPasswordForm" method="post" action="" class="form-horizontal">
                        <div class="form-group">
                            <?php echo $this->formLabel($new) ?>
                            <div class="col-sm-9">
                                <?php echo $this->formInput($new) ?>
                                <span style="display: none" class="help-block"><i class="fa fa-warning"></i> <?php echo $this->translate('application.user.new-password.password.help-block')?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <?php echo $this->formLabel($repeat) ?>
                            <div class="col-sm-9">
                                <?php echo $this->formInput($repeat) ?>
                                <span style="display: none" class="help-block"><i class="fa fa-warning"></i> <?php echo $this->translate('application.user.new-password.passwordRepeat.help-block')?></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <?php echo $this->formSubmit($form->get('submit')) ?>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-md-offset-3">
            <a href="<?php echo $this->url('zfcuser/login', [], true)?>"><?php echo $this->translate('Register.backLink')?></a>
        </div>
    </div>
</div>
<script type="text/javascript">
    Validator.initNewPassword();
</script>

