<?php
if (!$this->enableRegistration) {
    print $this->translate('application.user.register.registerIsDisabled');
    return;
}

$helpBlockMessages = array(
    'firstName' => $this->translate('application.user.register.firstName.help-block'),
    'lastName' => $this->translate('application.user.register.lastName.help-block'),
    'phone' => $this->translate('application.user.register.phone.help-block'),
    'personalCode' => $this->translate('application.user.register.personalCode.help-block'),
    'email' => $this->translate('application.user.register.email.help-block'),
    'password' => $this->translate('application.user.register.password.help-block'),
    'passwordRepeat' => $this->translate('application.user.register.password.help-block'),
);

$form = $this->registerForm;
$form->setAttribute('action', $this->url('zfcuser/register', [], true));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('id', 'registerForm');
?>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-2">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"><?php echo $this->translate('application.user.register.heading')?></h3>
                </div>
                <div class="panel-body">
                    <?php echo $this->form()->openTag($form) ?>
                        <?php foreach ($form as $element): ?>
                            <?php if (!$element instanceof Zend\Form\Element\Submit): ?>
                                <div class="form-group">
                                    <?php echo $this->formLabel($element) ?>
                                    <div class="col-sm-9">
                                        <?php echo $this->formInput($element) ?>
                                        <span style="display: none" class="help-block"><i class="fa fa-warning"></i> <?php echo $helpBlockMessages[$element->getName()]?></span>
                                    </div>
                                </div>
                            <?php endif ?>
                        <?php endforeach ?>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-9">
                                <?php echo $this->formSubmit($form->get('submit')) ?>
                            </div>
                        </div>
                    <?php echo $this->form()->closeTag() ?>
                </div>
            </div>
        </div>
        <div class="col-md-6 col-md-offset-3">
            <a href="<?php echo $this->url('zfcuser/login', [], true)?>"><?php echo $this->translate('Register.backLink')?></a>
        </div>
    </div>
</div>
<script type="text/javascript">
    Validator.initRegister();
</script>
