<div class="col-sm-3"></div>
<div class="col-sm-6">
    <div class="modal-content">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Article.category.list.add.modalHeading')?>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <form id="categoryForm" class="form-horizontal" method="post" action="<?php echo $this->url('add-category', [], true)?>" enctype="multipart/form-data">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('name'))?>
                        <div class="col-sm-9">
                            <?php echo $this->formText($form->get('name'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('code'))?>
                        <div class="col-sm-9">
                            <?php echo $this->formText($form->get('code'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('description'))?>
                        <div class="col-sm-9">
                            <?php echo $this->formTextArea($form->get('description'))?>
                        </div>
                    </div>
                    <input type="hidden" name="status" value="<?php echo \Application\Entity\Article\Category::STATUS_ACTIVE?>">
                    <div class="form-actions pull-right">
                        <div class="row">
                            <div class="col-sm-12">
                                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">
                                    <?php echo $this->translate('Article.category.list.add.modal.cancelButton')?>
                                </button>
                                <button class="btn btn-primary btn-sm" id="add-category-submit"  type="submit">
                                    <i class="fa fa-save"></i>
                                    <?php echo $this->translate('Article.category.list.add.modal.saveButton')?>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
<script type="text/javascript">
    Validator.initCategoryForm();
</script>