<div class="col-sm-12">
    <div class="modal-content">
        <div class="panel panel-default">
            <div id="panel-heading" class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Client.add.heading')?>
            </div>
            <!-- /.panel-heading -->
            <div id="panel-body" class="panel-body">
                <form id="clientForm" class="form-horizontal" method="post" action="<?php echo $this->url('add-client', [], true)?>" >
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('name'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('name'))?>
                        </div>
                        <?php echo $this->formLabel($form->get('code'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('code'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('email'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('email'))?>
                        </div>
                        <?php echo $this->formLabel($form->get('regNo'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('regNo'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('phone'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('phone'))?>
                        </div>
                        <?php echo $this->formLabel($form->get('vatNo'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('vatNo'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('delayPercent'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('delayPercent'))?>
                        </div>
                        <?php echo $this->formLabel($form->get('deadlineDays'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('deadlineDays'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('clientUser'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formSelect($form->get('clientUser'))?>
                        </div>
                        <?php echo $this->formLabel($form->get('referenceNumber'))?>
                        <div class="col-sm-4">
                            <?php echo $this->formText($form->get('referenceNumber'))?>
                        </div>
                    </div>
                    <input type="hidden" name="status" value="<?php echo \Application\Entity\Subject\Client::STATUS_ACTIVE?>">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('address'))?>
                        <div class="col-sm-10">
                            <?php echo $this->formTextArea($form->get('address'))?>
                        </div>
                    </div>
                    <div class="form-actions pull-right">
                        <div class="row">
                            <div class="col-sm-12">
                                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">
                                    <?php echo $this->translate('Client.add.cancelButton')?>
                                </button>
                                <button class="btn btn-primary btn-sm" id="add-client-submit"  type="submit">
                                    <i class="fa fa-save"></i>
                                    <?php echo $this->translate('Client.add.saveButton')?>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
<script type="text/javascript">
    Validator.initClientForm();
</script>