<div class="col-sm-3"></div>
<div class="col-sm-6">
    <div class="modal-content">
        <div class="panel panel-default">
            <div id="panel-heading" class="panel-heading">
                <i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->translate('Article.unit.list.add.modalHeading')?>
            </div>
            <!-- /.panel-heading -->
            <div id="panel-body" class="panel-body">
                <form id="unitForm" class="form-horizontal" method="post">
                    <div class="form-group">
                        <?php echo $this->formLabel($form->get('code'))?>
                        <div class="col-sm-8">
                            <?php echo $this->formText($form->get('code'))?>
                        </div>
                        <input type="hidden" name="status" value="<?php echo \Application\Entity\Unit::STATUS_ACTIVE?>">
                    </div>
                    <div class="form-actions pull-right">
                        <div class="row">
                            <div class="col-sm-12">
                                <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">
                                    <?php echo $this->translate('Article.unit.list.add.modal.cancelButton')?>
                                </button>
                                <button class="btn btn-primary btn-sm" id="add-unit-submit"  type="submit">
                                    <i class="fa fa-save"></i>
                                    <?php echo $this->translate('Article.unit.list.add.modal.saveButton')?>
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
<div class="col-sm-3"></div>
<script type="text/javascript">
    Validator.initUnitForm();
</script>